### ISSUE TITLE
New Export CSV in form [week #, mon, tue, ... sun, sum]

### ISSUE THREAD

**Issue by AlexShafir** [adrcotfas/Goodtime#162]
**Current behaviour:**
When exporting in CSV, output is [time-of-completion, time, label]

**Enchancement:**
Output in form [week #, mon, tue, ... sun, sum].

**Why:**
Currently I re-arrange exported CSV because plain list of times is not very useful.

**Comment by adrcotfas** [comment]
The current format is yyyy-MM-dd-HH-mm which can be sorted chronologically and contains all the information about when the session was finished.
Are you proposing to have a new column for week and one for day?
I wouldn't add "sum" because you may have different labels associated to different sessions. I would leave the CSV processing to the users if they have custom needs like sorting by date, sorting by label, calculating a sum, all of which can be easily done using the available data.

**Comment by AlexShafir** [comment]
I think I need to be a bit more precise: I would like to CSV being arranged by rows, where each row represents week. So that there will be 8 columns: 1 for week number and 7 for week days.

Example:

|  Week No | Mn  | Td  | Wd  | Th  | Fr  |  St | Sn  | Sum |
|---|---|---|---|---|---|---|---| ---|
|  # 1 | 0 | 2 | 4 | 5 | 3  | 0 | 0 | 14 |
|  # 2 | 1 |  0 | 5  |  2 | 1  | 1  | 0  | 10 |

This task cannot be achieved using chronological order. Currently I manually fill this weekday table from CSV app output.

It seems to me that for much people (definetely not for all) life is arranged on per-week basis. So that these people (like me) could be interested in weekly work patterns and how much time they spent overall throughout the week.

This output option can be in addition to current list CSV output option.

**Comment by adrcotfas** [comment]
It wouldn't be difficult to automate your need with a script that takes the CSV exported from Goodtime as input.
I won't implement this inside the app because it's quite a specific layout and would require additional runtime.
