### ISSUE TITLE
Only Click Once on Choosing a Label

### ISSUE THREAD

**Issue by r4taw2mg** [adrcotfas/Goodtime#187]
When you are choosing a label, you click the label and have to confirm by clicking "OK". I think this last click on "OK" can be removed. Maybe it would be a good idea, to show the active label together with the remaining time?

**Comment by adrcotfas** [comment]
There's the option to have no label at all so that wouldn't work with your proposal.
You can also select the profile from the label selection dialog so removing that "Ok" would make it confusing.
Why would you want to see the remaining time? That is visible on the main screen or in the ongoing notification.

**Comment by r4taw2mg** [comment]
It would still be possible, just have a fixed entry "none".

I have just now seen, that you can select the profile form that same dialogue, I was assuming, this is just a display. My personal preference would be, to show the profile on the main screen and make this display selectable.

Sorry, I was not precise about the second part. I was proposing to show the label together with the running time on the main screen. That way a quick glance on the clock would also show what to focus on.

**Comment by hvhaugwitz** [comment]
What about to open a label quick selection dialog (where you can directly choose the label from the list) on long press on the current active label?
