### ISSUE TITLE
App crashing on google pixel 2, Android 10, when trying to change default sound

### ISSUE THREAD

**Issue by bigcattus** [adrcotfas/Goodtime#192]
To reproduce, try to change from default notification sound in "Finished work/break notification".
Goodtime version 2.1.13.

**Comment by adrcotfas** [comment]
Did you by any chance update to Android 10 recently after already using the app with custom sounds?

**Comment by bigcattus** [comment]
No, I installed the app onto a phone already running Android 10.  If I could do anything to debug this further, please let me know.  Thanks.

**Comment by natrius** [comment]
Used this app already on a Xiaomi Mi 9 with Android 10 succesfully. Was able to choose some sounds. 

Since the last update (via F-Droid) the sounds are gone (no audio) and with "Finished work notification" i can choose between "Default notification sound", "ring.ogg" and "Add ringtone" but i cannot choose anymore from the other sounds. 

Anyway, when trying to get "Finished break notification", the app just g ets direct to the main screen without doing anything.

**Comment by adrcotfas** [comment]
@natrius What version were you using before?

**Comment by natrius** [comment]
2.1.13 - i'm using that one now again and its working.

**Comment by natrius** [comment]
I updated right now via F-Droid again to 2.1.14 and now i can choose a song without the app going back to the main-screen. *shrug*

**Comment by adrcotfas** [comment]
@bigcattus Is this still reproducible for you?

**Comment by bigcattus** [comment]
Yes, it is. I have a different phone now, pixel 3, but same system, Android 10

**Comment by adrcotfas** [comment]
This should be fixed now as I changed the Ringtone library.
