### ISSUE TITLE
Timer should run as separate service

### ISSUE THREAD

**Issue by wolfgang42** [adrcotfas/Goodtime#22]
I often use my phone for tasks while working, which means that the Goodtime app winds up in the background and Android sometimes decides to pause it. (To reproduce this consistently, enable Settings > Developer options > Don't keep activities.) This means that I'll sometimes notice half an hour later that there's still 15 minutes left of a 25-minute session.

I tried to fix this myself, but I got confused trying to understand how the preferences are set up. Is there a particular reason that some of the preferences (e.g. `mSessionTime`, `mBreakTime`, `mDisableWifi`) are stored in variables and saved into the bundle instead of using `mPref.get*()` each time they're needed?

**Comment by adrcotfas** [comment]
There is no particular reason for storing them as members and that part can be refactored.

**Comment by adrcotfas** [comment]
What do you think about using the AlarmManager instead of running the timer as a service?

**Comment by wolfgang42** [comment]
Excellent point, `AlarmManager` is probably a better way of implementing this. I said "hmm, this code should be running but isn't" and jumped immediately to services before considering other options.

**Comment by fdw** [comment]
Regardless of using an `AlarmManager` or not, I think we need a service to manage the timers. Right now, the `MainActivity` has (at least) two responsibilities: Drawing and updating the GUI, and managing the timers. From an architectural point of view, this should be separated, possibly into an Activity and a Service:
Since we also want a widget (#3), and actionable notification (#35), these would be just another gui to manage the timers. All three of these GUIs could then interact with the TimerService (or whatever it is called) to start and stop them and probably ask for the remaining time.
The TimerService is responsible for disabling sound and wifi, keeping track of streaks and stats, and starting the Timer itself.

**Comment by adrcotfas** [comment]
Hi, can you guys do a review of 935475a3a85af79a344e5510100a68815df47ed4 ?

**Comment by fdw** [comment]
Hi @adrcotfas,
I had a quick look around, and the short of it is that this should work correctly :)

However, I'd suggest some more changes:
* Maybe manage the "in progress" notification in the service, instead of the GUI. `startForeground()` should also stop the system from killing the service.
* Why are you sending two `Intents` when the session is finished. I think one Intent with `remainingTime` set to zero should be enough, shouldn't it?
* Perhaps we should save the wifi and sound states in the timer, when a session is started, and not when the app itself starts. I had some annoying run in when "Do no disturb" automatically activated (based on the time), but Goodtime reset the sound settings back to before. (This should probably be a separate issue.)
* In my personal opinion, a commit should only change one thing, but yours also adds some translations. I have no problem with this (it is your code, after all), but I'd suggest splitting commits in the future. I also love `git add -p` for this 😃 

All in all: Good work 👍

**Comment by adrcotfas** [comment]
Thanks for the ideas, @fdw !

I just realized that moving the timer to a Service will not make it run in a separate Thread. The TimerService, as it is now, will run on the UI thread so there is still work to do in that area.

P.S.
The branch does contain several separated commits: https://github.com/adrcotfas/Goodtime/compare/create-timer-service.
Indeed, the name is related to the Service.

**Comment by fdw** [comment]
Oh, sorry, I thought I was looking at only one commit. My apologies!

**Comment by adrcotfas** [comment]
Fixed with #40

**Comment by fdw** [comment]
One more question: Do you have any plans for the translations? Should I add German back?

**Comment by adrcotfas** [comment]
Not yet. The German translation is not complete because I added more strings to be translated, including the app page description from Play. I'll add translation when they will be complete.
https://poeditor.com/projects/view?id=75697
