### ISSUE TITLE
Feature Request: Possibility to extend work time.

### ISSUE THREAD

**Issue by lucmaga** [adrcotfas/Goodtime#232]
I would benefit from a button on the "start break" box to extend work time indefinitely or for a certain amount of time (maybe configurable).

**Comment by adrcotfas** [comment]
This feature was request in the past and a similar effect is already in place:
Manually extending a session by swiping up on the timer to add extra minutes and the pre-notification added in 2.2.0 so the users get the opportunity to extend the current work session.  

I have no plans of adding an "extend" button in the start break dialog because sessions are stored to the statistics at the end. Extending a session after it's finished would complicate the statistics database handling.
