### ISSUE TITLE
[Feature Request] Add ability to attach small text notes to sessions

### ISSUE THREAD

**Issue by 6y6eH4uk** [adrcotfas/Goodtime#319]
Currently, the only way to annotate a session is to use a single label, which is very convenient. However, it becomes inadequate when you need to analyze each session individually in the future. It would be beneficial to allow attaching a small plain text note from "TextArea" to each session.

For instance, I have a tag for marking sessions related to reading articles online. I'd like to add the title of the article to each session without creating separate labels for each article. After adding a note, I can easily review all my notes through the list of sessions.

While it might be challenging to navigate through the session list to find specific notes, the primary purpose of these notes is to provide details about particular sessions on specific dates.

Personally, I intend to use such notes to periodically summarize my productivity at the end of each week or month.

**Comment by 6y6eH4uk** [comment]
I think I'm missing the author's original intent. While I have a hard time agreeing with the idea, maybe it would be possible to create tags for any little things? And then archive them and forget about them forever?

**Comment by Korb** [comment]
> I think I'm missing the author's original intent. While I have a hard time agreeing with the idea, maybe it would be possible to create tags for any little things? And then archive them and forget about them forever?

I'm trying to figure out the purpose of entities like `Labels` and `Notes` in the app. Your first message helped me a bit, but the second one has me stumped. Could you please clarify what exactly you meant? "The author's original intent"—regarding what exactly? Labels or Notes? Apparently the former, since you suggested the latter, meaning the original idea was yours.

Is something preventing you from creating tags for any little thing now? Or are you against archiving them later? Or archiving is not supported by the application and you would like it to be so? Something else?

I'm completely confused by these entities, your claims, and your desires. 😅
